-- =========================================================
-- WEEK 9: SALES AND CUSTOMER ANALYTICS SYSTEM
-- E-COMMERCE DATABASE
-- =========================================================


-- =========================================================
-- 1. APPLY SQL AGGREGATE FUNCTIONS
-- =========================================================

-- Total number of customers
SELECT COUNT(*) AS Total_Customers
FROM customers;

-- Total number of orders
SELECT COUNT(*) AS Total_Orders
FROM orders;

-- Total revenue generated
SELECT SUM(Total_Amount) AS Total_Revenue
FROM orders;

-- Average order value
SELECT AVG(Total_Amount) AS Average_Order_Value
FROM orders;

-- Highest order amount
SELECT MAX(Total_Amount) AS Highest_Order_Amount
FROM orders;

-- Lowest order amount
SELECT MIN(Total_Amount) AS Lowest_Order_Amount
FROM orders;


-- =========================================================
-- 2. TOTAL SALES REPORTS
-- =========================================================

-- 1. Total number of orders placed
SELECT COUNT(*) AS Total_Orders
FROM orders;

-- 2. Total revenue generated from sales
SELECT SUM(Total_Amount) AS Total_Revenue
FROM orders;

-- 3. Average order value
SELECT AVG(Total_Amount) AS Average_Order_Value
FROM orders;

-- 4. Highest and lowest order amount
SELECT
    MAX(Total_Amount) AS Highest_Order_Amount,
    MIN(Total_Amount) AS Lowest_Order_Amount
FROM orders;

-- 5. Total sales for a specific period
-- Change the dates according to your database
SELECT SUM(Total_Amount) AS Period_Total_Sales
FROM orders
WHERE Order_Date BETWEEN '2026-01-01' AND '2026-12-31';


-- =========================================================
-- 3. CUSTOMER PURCHASE ANALYSIS
-- =========================================================

-- 1. Total number of orders placed by each customer
SELECT
    Customer_ID,
    COUNT(*) AS Total_Orders
FROM orders
GROUP BY Customer_ID;

-- 2. Total amount spent by each customer
SELECT
    Customer_ID,
    SUM(Total_Amount) AS Total_Spending
FROM orders
GROUP BY Customer_ID;

-- 3. Average spending per customer
SELECT
    Customer_ID,
    AVG(Total_Amount) AS Average_Spending
FROM orders
GROUP BY Customer_ID;

-- 4. Customers with maximum purchase amount
SELECT
    Customer_ID,
    SUM(Total_Amount) AS Total_Spending
FROM orders
GROUP BY Customer_ID
ORDER BY Total_Spending DESC;

-- 5. Customers with fewer purchases
SELECT
    Customer_ID,
    COUNT(*) AS Total_Orders
FROM orders
GROUP BY Customer_ID
ORDER BY Total_Orders ASC;


-- =========================================================
-- 4. TOP CUSTOMERS BASED ON PURCHASE AMOUNT
-- =========================================================

-- 1. Top 5 customers based on total spending
SELECT
    Customer_ID,
    SUM(Total_Amount) AS Total_Spending
FROM orders
GROUP BY Customer_ID
ORDER BY Total_Spending DESC
LIMIT 5;

-- 2. Customers with maximum number of orders
SELECT
    Customer_ID,
    COUNT(*) AS Total_Orders
FROM orders
GROUP BY Customer_ID
ORDER BY Total_Orders DESC;

-- 3. Frequent customers
SELECT
    Customer_ID,
    COUNT(*) AS Purchase_Frequency
FROM orders
GROUP BY Customer_ID
HAVING COUNT(*) > 1
ORDER BY Purchase_Frequency DESC;

-- 4. High-value customers
SELECT
    Customer_ID,
    SUM(Total_Amount) AS Total_Spending
FROM orders
GROUP BY Customer_ID
HAVING SUM(Total_Amount) > 10000
ORDER BY Total_Spending DESC;


-- =========================================================
-- 5. BEST-SELLING PRODUCTS
-- =========================================================

-- 1. Products with maximum sales quantity
SELECT
    Product_ID,
    SUM(Quantity) AS Total_Sold
FROM Order_Details
GROUP BY Product_ID
ORDER BY Total_Sold DESC;

-- 2. Products generating highest revenue
SELECT
    Product_ID,
    SUM(Quantity * Price) AS Revenue
FROM Order_Details
GROUP BY Product_ID
ORDER BY Revenue DESC;

-- 3. Least-selling products
SELECT
    Product_ID,
    SUM(Quantity) AS Total_Sold
FROM Order_Details
GROUP BY Product_ID
ORDER BY Total_Sold ASC;

-- 4. Products requiring promotion
SELECT
    Product_ID,
    SUM(Quantity) AS Total_Sold
FROM Order_Details
GROUP BY Product_ID
HAVING SUM(Quantity) <= 5
ORDER BY Total_Sold ASC;


-- =========================================================
-- 6. CATEGORY-WISE SALES ANALYSIS
-- =========================================================

-- 1. Total sales generated by each category
SELECT
    p.Category_ID,
    SUM(od.Quantity * od.Price) AS Category_Sales
FROM products p
JOIN Order_Details od
ON p.Product_ID = od.Product_ID
GROUP BY p.Category_ID
ORDER BY Category_Sales DESC;

-- 2. Number of products sold in each category
SELECT
    p.Category_ID,
    SUM(od.Quantity) AS Total_Products_Sold
FROM products p
JOIN Order_Details od
ON p.Product_ID = od.Product_ID
GROUP BY p.Category_ID
ORDER BY Total_Products_Sold DESC;

-- 3. Highest revenue-generating category
SELECT
    p.Category_ID,
    SUM(od.Quantity * od.Price) AS Total_Revenue
FROM products p
JOIN Order_Details od
ON p.Product_ID = od.Product_ID
GROUP BY p.Category_ID
ORDER BY Total_Revenue DESC
LIMIT 1;

-- 4. Average sales per category
SELECT
    p.Category_ID,
    AVG(od.Quantity * od.Price) AS Average_Sales
FROM products p
JOIN Order_Details od
ON p.Product_ID = od.Product_ID
GROUP BY p.Category_ID
ORDER BY Average_Sales DESC;


-- =========================================================
-- 7. BUSINESS ANALYTICS REPORT 1
-- SALES PERFORMANCE REPORT
-- =========================================================

SELECT
    SUM(Total_Amount) AS Total_Sales,
    COUNT(*) AS Number_Of_Orders,
    AVG(Total_Amount) AS Average_Order_Value,
    MAX(Total_Amount) AS Highest_Order_Value
FROM orders;


-- =========================================================
-- 8. BUSINESS ANALYTICS REPORT 2
-- CUSTOMER ANALYTICS REPORT
-- =========================================================

SELECT
    c.Customer_Name,
    COUNT(o.Order_ID) AS Number_Of_Orders,
    SUM(o.Total_Amount) AS Total_Spending,
    COUNT(o.Order_ID) AS Purchase_Frequency
FROM customers c
JOIN orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Spending DESC;


-- =========================================================
-- 9. BUSINESS ANALYTICS REPORT 3
-- PRODUCT PERFORMANCE REPORT
-- =========================================================

SELECT
    p.Product_Name,
    SUM(od.Quantity) AS Quantity_Sold,
    SUM(od.Quantity * od.Price) AS Revenue_Generated
FROM products p
JOIN Order_Details od
ON p.Product_ID = od.Product_ID
GROUP BY p.Product_ID, p.Product_Name
ORDER BY Revenue_Generated DESC;


-- =========================================================
-- 10. BUSINESS ANALYTICS REPORT 4
-- CATEGORY ANALYSIS REPORT
-- =========================================================

SELECT
    c.Category_Name,
    SUM(od.Quantity) AS Total_Products_Sold,
    SUM(od.Quantity * od.Price) AS Total_Revenue
FROM categories c
JOIN products p
ON c.Category_ID = p.Category_ID
JOIN Order_Details od
ON p.Product_ID = od.Product_ID
GROUP BY c.Category_ID, c.Category_Name
ORDER BY Total_Revenue DESC;
